# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easy_plot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 166)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -4, 621, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 30, 161, 95))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.a_min = QtWidgets.QLineEdit(self.groupBox_5)
        self.a_min.setGeometry(QtCore.QRect(5, 20, 59, 21))
        self.a_min.setObjectName("a_min")
        self.a_max = QtWidgets.QLineEdit(self.groupBox_5)
        self.a_max.setGeometry(QtCore.QRect(97, 20, 59, 21))
        self.a_max.setObjectName("a_max")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(65, 20, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.b_min = QtWidgets.QLineEdit(self.groupBox_5)
        self.b_min.setGeometry(QtCore.QRect(5, 45, 59, 21))
        self.b_min.setObjectName("b_min")
        self.b_max = QtWidgets.QLineEdit(self.groupBox_5)
        self.b_max.setGeometry(QtCore.QRect(97, 45, 59, 21))
        self.b_max.setObjectName("b_max")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(65, 45, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(65, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.c_max = QtWidgets.QLineEdit(self.groupBox_5)
        self.c_max.setGeometry(QtCore.QRect(97, 70, 59, 21))
        self.c_max.setObjectName("c_max")
        self.c_min = QtWidgets.QLineEdit(self.groupBox_5)
        self.c_min.setGeometry(QtCore.QRect(5, 70, 59, 21))
        self.c_min.setObjectName("c_min")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(90, 75, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 45, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 70, 81, 45))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.drop_fit = QtWidgets.QComboBox(self.groupBox_3)
        self.drop_fit.setGeometry(QtCore.QRect(0, 20, 81, 24))
        self.drop_fit.setObjectName("drop_fit")
        self.drop_fit.addItem("")
        self.drop_fit.addItem("")
        self.drop_fit.addItem("")
        self.drop_fit.addItem("")
        self.drop_fit.addItem("")
        self.bttn_load = QtWidgets.QPushButton(self.tab_2)
        self.bttn_load.setGeometry(QtCore.QRect(520, 41, 72, 32))
        self.bttn_load.setObjectName("bttn_load")
        self.drop_column = QtWidgets.QComboBox(self.tab_2)
        self.drop_column.setGeometry(QtCore.QRect(5, 90, 81, 24))
        self.drop_column.setObjectName("drop_column")
        self.drop_column.addItem("")
        self.drop_column.addItem("")
        self.drop_column.addItem("")
        self.drop_column.addItem("")
        self.bttn_exit = QtWidgets.QPushButton(self.tab_2)
        self.bttn_exit.setGeometry(QtCore.QRect(500, 70, 91, 51))
        self.bttn_exit.setObjectName("bttn_exit")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 70, 81, 45))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.drop_color = QtWidgets.QComboBox(self.groupBox_4)
        self.drop_color.setGeometry(QtCore.QRect(0, 20, 81, 24))
        self.drop_color.setObjectName("drop_color")
        self.drop_color.addItem("")
        self.drop_color.addItem("")
        self.drop_color.addItem("")
        self.drop_color.addItem("")
        self.drop_color.addItem("")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 75, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 70, 70, 45))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.isotope = QtWidgets.QLineEdit(self.groupBox_2)
        self.isotope.setGeometry(QtCore.QRect(5, 20, 59, 21))
        self.isotope.setObjectName("isotope")
        self.delimiter = QtWidgets.QLineEdit(self.tab_2)
        self.delimiter.setGeometry(QtCore.QRect(90, 90, 59, 21))
        self.delimiter.setObjectName("delimiter")
        self.folder_path = QtWidgets.QLineEdit(self.tab_2)
        self.folder_path.setGeometry(QtCore.QRect(100, 45, 421, 21))
        self.folder_path.setObjectName("folder_path")
        self.bttn_plot = QtWidgets.QPushButton(self.tab_2)
        self.bttn_plot.setGeometry(QtCore.QRect(410, 70, 91, 51))
        self.bttn_plot.setObjectName("bttn_plot")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 581, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Fit bounds"))
        self.label_5.setText(_translate("MainWindow", "< a <"))
        self.label_6.setText(_translate("MainWindow", "< b <"))
        self.label_7.setText(_translate("MainWindow", "< c <"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Special"))
        self.label_3.setText(_translate("MainWindow", "Delimiter"))
        self.label_2.setText(_translate("MainWindow", ".xlsx, .csv, .txt, ..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fit"))
        self.drop_fit.setItemText(0, _translate("MainWindow", "x^2"))
        self.drop_fit.setItemText(1, _translate("MainWindow", "exp"))
        self.drop_fit.setItemText(2, _translate("MainWindow", "linear"))
        self.drop_fit.setItemText(3, _translate("MainWindow", "sin"))
        self.drop_fit.setItemText(4, _translate("MainWindow", "sqrt"))
        self.bttn_load.setText(_translate("MainWindow", "Load"))
        self.drop_column.setItemText(0, _translate("MainWindow", "x-y-yerr"))
        self.drop_column.setItemText(1, _translate("MainWindow", "x-y"))
        self.drop_column.setItemText(2, _translate("MainWindow", "y-x"))
        self.drop_column.setItemText(3, _translate("MainWindow", "x-xerr-y-yerr"))
        self.bttn_exit.setText(_translate("MainWindow", "Exit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Color"))
        self.drop_color.setItemText(0, _translate("MainWindow", "green"))
        self.drop_color.setItemText(1, _translate("MainWindow", "blue"))
        self.drop_color.setItemText(2, _translate("MainWindow", "black"))
        self.drop_color.setItemText(3, _translate("MainWindow", "red"))
        self.drop_color.setItemText(4, _translate("MainWindow", "yellow"))
        self.label.setText(_translate("MainWindow", "Columns"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Isotope"))
        self.bttn_plot.setText(_translate("MainWindow", "Plot"))
        self.label_4.setText(_translate("MainWindow", "Easy plotter: Select a file, change some options and plot. Fit is integrated in the figure\'s zoom button."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "General"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

