# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'piicr_analysis_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 240, 236, 91))
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.x_max = QtWidgets.QLineEdit(self.groupBox)
        self.x_max.setGeometry(QtCore.QRect(170, 30, 59, 21))
        self.x_max.setObjectName("x_max")
        self.y_max = QtWidgets.QLineEdit(self.groupBox)
        self.y_max.setGeometry(QtCore.QRect(170, 60, 59, 21))
        self.y_max.setObjectName("y_max")
        self.x_min = QtWidgets.QLineEdit(self.groupBox)
        self.x_min.setGeometry(QtCore.QRect(110, 30, 59, 21))
        self.x_min.setObjectName("x_min")
        self.y_min = QtWidgets.QLineEdit(self.groupBox)
        self.y_min.setGeometry(QtCore.QRect(110, 60, 59, 21))
        self.y_min.setObjectName("y_min")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(0, 60, 111, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 240, 146, 91))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tof_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.tof_max.setGeometry(QtCore.QRect(80, 60, 59, 21))
        self.tof_max.setObjectName("tof_max")
        self.tof_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.tof_min.setGeometry(QtCore.QRect(80, 30, 59, 21))
        self.tof_min.setObjectName("tof_min")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 30, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(0, 60, 81, 16))
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(430, 240, 146, 91))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.z_class_max = QtWidgets.QLineEdit(self.groupBox_3)
        self.z_class_max.setGeometry(QtCore.QRect(80, 60, 59, 21))
        self.z_class_max.setObjectName("z_class_max")
        self.z_class_min = QtWidgets.QLineEdit(self.groupBox_3)
        self.z_class_min.setGeometry(QtCore.QRect(80, 30, 59, 21))
        self.z_class_min.setObjectName("z_class_min")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(0, 30, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(0, 60, 81, 16))
        self.label_13.setObjectName("label_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 591, 241))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 543, 101))
        self.label_2.setObjectName("label_2")
        self.isotope4 = QtWidgets.QLineEdit(self.tab)
        self.isotope4.setGeometry(QtCore.QRect(358, 150, 59, 21))
        self.isotope4.setObjectName("isotope4")
        self.isotope5 = QtWidgets.QLineEdit(self.tab)
        self.isotope5.setGeometry(QtCore.QRect(427, 150, 59, 21))
        self.isotope5.setObjectName("isotope5")
        self.folder_path = QtWidgets.QLineEdit(self.tab)
        self.folder_path.setGeometry(QtCore.QRect(13, 115, 471, 21))
        self.folder_path.setObjectName("folder_path")
        self.load = QtWidgets.QPushButton(self.tab)
        self.load.setGeometry(QtCore.QRect(490, 111, 72, 32))
        self.load.setObjectName("load")
        self.isotope2 = QtWidgets.QLineEdit(self.tab)
        self.isotope2.setGeometry(QtCore.QRect(220, 150, 59, 21))
        self.isotope2.setObjectName("isotope2")
        self.isotope1 = QtWidgets.QLineEdit(self.tab)
        self.isotope1.setGeometry(QtCore.QRect(151, 150, 59, 21))
        self.isotope1.setObjectName("isotope1")
        self.run = QtWidgets.QPushButton(self.tab)
        self.run.setGeometry(QtCore.QRect(490, 146, 71, 32))
        self.run.setObjectName("run")
        self.isotope3 = QtWidgets.QLineEdit(self.tab)
        self.isotope3.setGeometry(QtCore.QRect(289, 150, 59, 21))
        self.isotope3.setObjectName("isotope3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(13, 150, 122, 16))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(10, 210, 541, 21))
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_ellipse = QtWidgets.QCheckBox(self.tab)
        self.checkBox_ellipse.setGeometry(QtCore.QRect(10, 180, 541, 21))
        self.checkBox_ellipse.setAutoRepeat(False)
        self.checkBox_ellipse.setTristate(False)
        self.checkBox_ellipse.setObjectName("checkBox_ellipse")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, -10, 543, 101))
        self.label_10.setObjectName("label_10")
        self.load_2 = QtWidgets.QPushButton(self.tab_2)
        self.load_2.setGeometry(QtCore.QRect(490, 80, 72, 32))
        self.load_2.setObjectName("load_2")
        self.run_3 = QtWidgets.QPushButton(self.tab_2)
        self.run_3.setGeometry(QtCore.QRect(490, 155, 71, 32))
        self.run_3.setObjectName("run_3")
        self.file_names = QtWidgets.QTextEdit(self.tab_2)
        self.file_names.setGeometry(QtCore.QRect(10, 80, 471, 101))
        self.file_names.setObjectName("file_names")
        self.isotope1_2 = QtWidgets.QLineEdit(self.tab_2)
        self.isotope1_2.setGeometry(QtCore.QRect(495, 130, 59, 21))
        self.isotope1_2.setObjectName("isotope1_2")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(500, 110, 51, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 330, 556, 71))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(5, 25, 491, 16))
        self.label_16.setObjectName("label_16")
        self.load_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.load_3.setGeometry(QtCore.QRect(480, 40, 72, 32))
        self.load_3.setObjectName("load_3")
        self.folder_path_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.folder_path_2.setGeometry(QtCore.QRect(3, 44, 471, 21))
        self.folder_path_2.setObjectName("folder_path_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 591, 191))
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 543, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.ref = QtWidgets.QLineEdit(self.layoutWidget)
        self.ref.setObjectName("ref")
        self.horizontalLayout.addWidget(self.ref)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.meas = QtWidgets.QLineEdit(self.layoutWidget)
        self.meas.setObjectName("meas")
        self.horizontalLayout.addWidget(self.meas)
        self.run_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.run_2.setObjectName("run_2")
        self.horizontalLayout.addWidget(self.run_2)
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 526, 71))
        self.label_3.setObjectName("label_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 105, 341, 76))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.ground_or_isomer = QtWidgets.QLineEdit(self.groupBox_5)
        self.ground_or_isomer.setGeometry(QtCore.QRect(165, 25, 71, 21))
        self.ground_or_isomer.setObjectName("ground_or_isomer")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(5, 25, 161, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(5, 50, 161, 21))
        self.label_15.setObjectName("label_15")
        self.isomer_mass_excess = QtWidgets.QLineEdit(self.groupBox_5)
        self.isomer_mass_excess.setGeometry(QtCore.QRect(165, 50, 71, 21))
        self.isomer_mass_excess.setObjectName("isomer_mass_excess")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.label_17.setObjectName("label_17")
        self.isomer_mass_excess_unc = QtWidgets.QLineEdit(self.groupBox_5)
        self.isomer_mass_excess_unc.setGeometry(QtCore.QRect(265, 50, 71, 21))
        self.isomer_mass_excess_unc.setObjectName("isomer_mass_excess_unc")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(10, 0, 531, 71))
        self.label_27.setObjectName("label_27")
        self.run_8 = QtWidgets.QPushButton(self.tab_6)
        self.run_8.setGeometry(QtCore.QRect(490, 140, 71, 32))
        self.run_8.setObjectName("run_8")
        self.load_5 = QtWidgets.QPushButton(self.tab_6)
        self.load_5.setGeometry(QtCore.QRect(490, 110, 72, 32))
        self.load_5.setObjectName("load_5")
        self.folder_paths = QtWidgets.QTextEdit(self.tab_6)
        self.folder_paths.setGeometry(QtCore.QRect(10, 80, 471, 101))
        self.folder_paths.setObjectName("folder_paths")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.exit_bttn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_bttn.setGeometry(QtCore.QRect(600, 10, 41, 421))
        self.exit_bttn.setObjectName("exit_bttn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menuHelp)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfdsa = QtWidgets.QAction(MainWindow)
        self.actionfdsa.setObjectName("actionfdsa")
        self.action2017_Jonas_Karthein_Questions_comments_to_jonas_karthein_cern_ch = QtWidgets.QAction(MainWindow)
        self.action2017_Jonas_Karthein_Questions_comments_to_jonas_karthein_cern_ch.setObjectName("action2017_Jonas_Karthein_Questions_comments_to_jonas_karthein_cern_ch")
        self.menuFile.addAction(self.actionfdsa)
        self.menuAbout.addAction(self.action2017_Jonas_Karthein_Questions_comments_to_jonas_karthein_cern_ch)
        self.menuHelp.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.folder_path, self.load)
        MainWindow.setTabOrder(self.load, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.isotope1)
        MainWindow.setTabOrder(self.isotope1, self.isotope2)
        MainWindow.setTabOrder(self.isotope2, self.isotope3)
        MainWindow.setTabOrder(self.isotope3, self.isotope4)
        MainWindow.setTabOrder(self.isotope4, self.isotope5)
        MainWindow.setTabOrder(self.isotope5, self.run)
        MainWindow.setTabOrder(self.run, self.groupBox)
        MainWindow.setTabOrder(self.groupBox, self.x_min)
        MainWindow.setTabOrder(self.x_min, self.x_max)
        MainWindow.setTabOrder(self.x_max, self.y_min)
        MainWindow.setTabOrder(self.y_min, self.y_max)
        MainWindow.setTabOrder(self.y_max, self.groupBox_2)
        MainWindow.setTabOrder(self.groupBox_2, self.tof_min)
        MainWindow.setTabOrder(self.tof_min, self.tof_max)
        MainWindow.setTabOrder(self.tof_max, self.groupBox_3)
        MainWindow.setTabOrder(self.groupBox_3, self.z_class_min)
        MainWindow.setTabOrder(self.z_class_min, self.z_class_max)
        MainWindow.setTabOrder(self.z_class_max, self.groupBox_4)
        MainWindow.setTabOrder(self.groupBox_4, self.folder_path_2)
        MainWindow.setTabOrder(self.folder_path_2, self.load_3)
        MainWindow.setTabOrder(self.load_3, self.exit_bttn)
        MainWindow.setTabOrder(self.exit_bttn, self.ref)
        MainWindow.setTabOrder(self.ref, self.meas)
        MainWindow.setTabOrder(self.meas, self.run_2)
        MainWindow.setTabOrder(self.run_2, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.load_2)
        MainWindow.setTabOrder(self.load_2, self.run_3)
        MainWindow.setTabOrder(self.run_3, self.file_names)
        MainWindow.setTabOrder(self.file_names, self.isotope1_2)
        MainWindow.setTabOrder(self.isotope1_2, self.tabWidget_3)
        MainWindow.setTabOrder(self.tabWidget_3, self.run_8)
        MainWindow.setTabOrder(self.run_8, self.load_5)
        MainWindow.setTabOrder(self.load_5, self.folder_paths)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PI-ICR analysis"))
        self.groupBox.setTitle(_translate("MainWindow", "Position fit cut:"))
        self.label_6.setText(_translate("MainWindow", "X [min, max] / ch."))
        self.label_7.setText(_translate("MainWindow", "Y [min, max] / ch."))
        self.groupBox_2.setTitle(_translate("MainWindow", "ToF cut:"))
        self.label_8.setText(_translate("MainWindow", "ToF min / μs"))
        self.label_9.setText(_translate("MainWindow", "ToF max / μs"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Z-class analysis:"))
        self.label_12.setText(_translate("MainWindow", "Min # / shot"))
        self.label_13.setText(_translate("MainWindow", "Max # / shot"))
        self.label_2.setText(_translate("MainWindow", "PI-ICR spot reconstruction and frequency calculation V2.1:\n"
"\n"
"Did you run \"piicr_timestamps.exe\" to add the timestamps to the raw data?\n"
"\n"
"Just put all the files (center file, p1p2 files, frequency config file [.out]) into one folder and\n"
"select it. Then provide information about the isotopes (e.g. \'85Rb\') and klick \'Run\'."))
        self.load.setText(_translate("MainWindow", "Load"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Enter isotopes here:"))
        self.checkBox.setText(_translate("MainWindow", "Isomer analysis: simultaneous 2D gaussian fit for both ground and isomer (P2 spot)"))
        self.checkBox_ellipse.setText(_translate("MainWindow", "Manual spot selection (Click+hold ellipse selector)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Batch"))
        self.label_10.setText(_translate("MainWindow", "PI-ICR spot reconstruction and frequency calculation V2.1:\n"
"\n"
"Did you run \"piicr_timestamps.exe\" to add the timestamps to the raw data?\n"
"Select a file to fit and klick \'Run\'."))
        self.load_2.setText(_translate("MainWindow", "Load"))
        self.run_3.setText(_translate("MainWindow", "Run"))
        self.label_11.setText(_translate("MainWindow", "Isotope:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Single"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Fix FWHM fit parameter"))
        self.label_16.setText(_translate("MainWindow", "Load \"_all_peak_positions_c.csv\" of reference ion used for FWHM parameter fix"))
        self.load_3.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "PI-ICR-fitting"))
        self.label_4.setText(_translate("MainWindow", "Enter REF here:"))
        self.label_5.setText(_translate("MainWindow", "Enter MEAS here:"))
        self.run_2.setText(_translate("MainWindow", "Go!"))
        self.label_3.setText(_translate("MainWindow", "PI-ICR cross-check calculation V2.1:\n"
"\n"
"Just select which isotope should be the measurement ion and which one should be the\n"
"reference ion. Finally click \'Go!\'."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Isomer-analysis"))
        self.label_14.setText(_translate("MainWindow", "Enter \'ground\' or \'isomer\':"))
        self.label_15.setText(_translate("MainWindow", "Mass excess / keV :"))
        self.label_17.setText(_translate("MainWindow", "+/-"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Single"))
        self.label_27.setText(_translate("MainWindow", "PI-ICR cross-check combination V2.1:\n"
"\n"
"If you want to combine multiple cross-checks of a run or even multiple runs just select\n"
"the run-folders (same as in fitting) of the runs you want to combine and klick \'Go!\'."))
        self.run_8.setText(_translate("MainWindow", "Go!"))
        self.load_5.setText(_translate("MainWindow", "Load"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Combined"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Cross-checks"))
        self.exit_bttn.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionfdsa.setText(_translate("MainWindow", "Exit"))
        self.action2017_Jonas_Karthein_Questions_comments_to_jonas_karthein_cern_ch.setText(_translate("MainWindow", "2017 Jonas Karthein. Questions/comments to jonas.karthein@cern.ch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

